[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Will Bickford <wbic16@gmail.com>"]

[workspace.dependencies]
libphext = { path = "/source/libphext-rs" }
memmap2 = "0.9"
rayon = "1.10"
criterion = { version = "0.5", features = ["html_reports"] }
crossterm = "0.28"
ratatui = "0.29"
gpui = "0.2"
